---
title: Shiny App Review
author: Samuel Lyubic
date: '2020-10-15'
slug: shiny-app-review
categories:
  - Corona
  - Covid
  - App
  - Review
tags:
  - Coronavirus
  - Review
  - United Kingdom
  - Ireland
subtitle: 'App review of cone smoking and blunt hitting'
summary: ''
authors: []
lastmod: '2020-10-15T15:13:36+11:00' 
featured: no
image:   
  placement: 3
  caption: ''
  focal_point: ''
projects: []
---

## What is _"Covid19: The Battle of Independence" app all bout?"_

The _"Covid19: The Battle of Independence" app all bout?"_ is an application that focuses on compartive analysis of the impact and response to corona virus between Ireland and the United Kingdom. There is a long standing and divisive history of conflict and war between the two countries that stems from Ireland's plight for seeking their independence from the United Kingdom, which has thus far been unsuccesful. Given the stability and economic assistance that the Republic of Ireland recieves by being apart of the United Kingdom there are many pundits for and against the Republic's indepedence however, key individuals who are pro independence are presenting the impact and response to coronavirus between Ireland and the United Kingdom as a case study to further ignite and push the fight for independence, with the difference in impact and response between the two countries acting as a proxy for Ireland's ability to stand completely independent.As a follow on from my blog post [_"Success in the face of coronavirus? Maybe."_](http://127.0.0.1:4321/post/blog_two/blog-post-two-ireland/) this application provides the user with interactive tools to analyse and compare a range of coronavirus statistics and responses between the two countries and assess the case study for themeselves. 

